project:
  type: website

website:
  title: "Rabbitholes"
  description: "Sarah Pan spends too much time doing random things"
  navbar:
    background: light
    search: false
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      light: [cosmo, styles.css]
    toc: true
    code-copy: true
    anchor-sections: true

page-layout: full



